"""updating visibility table

Revision ID: 53b42a54af3d
Revises: f52971122624
Create Date: 2026-01-26 14:32:29.876741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53b42a54af3d'
down_revision: Union[str, Sequence[str], None] = 'f52971122624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_visibility', sa.Column('date', sa.Date(), nullable=False))
    op.drop_index(op.f('ix_site_visibility_time_bucket'), table_name='site_visibility')
    op.drop_index(op.f('ix_site_visibility_time_score'), table_name='site_visibility')
    op.create_index(op.f('ix_site_visibility_date'), 'site_visibility', ['date'], unique=False)
    op.create_index('ix_site_visibility_date_score', 'site_visibility', ['date', 'score'], unique=False)
    op.drop_column('site_visibility', 'time_bucket')
    op.drop_column('site_visibility', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_visibility', sa.Column('category', postgresql.ENUM('Perfect', 'Amazing', 'Great', 'Good', 'Ok', 'Bad', 'Terrible', name='sitevisibility'), autoincrement=False, nullable=False))
    op.add_column('site_visibility', sa.Column('time_bucket', postgresql.ENUM('NOW', 'TONIGHT', 'TOMORROW_NIGHT', 'NIGHTS_3_FROM_NOW', name='timevisibility'), autoincrement=False, nullable=False))
    op.drop_index('ix_site_visibility_date_score', table_name='site_visibility')
    op.drop_index(op.f('ix_site_visibility_date'), table_name='site_visibility')
    op.create_index(op.f('ix_site_visibility_time_score'), 'site_visibility', ['time_bucket', 'score'], unique=False)
    op.create_index(op.f('ix_site_visibility_time_bucket'), 'site_visibility', ['time_bucket'], unique=False)
    op.drop_column('site_visibility', 'date')
    # ### end Alembic commands ###
