"""adding source fields to sitedb

Revision ID: 51c4e5007b52
Revises: c5b3a2b99639
Create Date: 2026-01-15 10:34:27.909138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c4e5007b52'
down_revision: Union[str, Sequence[str], None] = 'c5b3a2b99639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('source', sa.String(), nullable=True))
    op.add_column('sites', sa.Column('source_ref', sa.String(), nullable=True))
    op.add_column('sites', sa.Column('category', sa.String(), nullable=True))
    op.add_column('sites', sa.Column('notes', sa.JSON(), nullable=True))
    op.create_unique_constraint('uq_sites_source', 'sites', ['source', 'source_ref'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sites_source', 'sites', type_='unique')
    op.drop_column('sites', 'notes')
    op.drop_column('sites', 'category')
    op.drop_column('sites', 'source_ref')
    op.drop_column('sites', 'source')
    # ### end Alembic commands ###
