"""adding visibility table

Revision ID: f52971122624
Revises: 51c4e5007b52
Create Date: 2026-01-15 12:58:51.114097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52971122624'
down_revision: Union[str, Sequence[str], None] = '51c4e5007b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_visibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('time_bucket', sa.Enum('NOW', 'TONIGHT', 'TOMORROW_NIGHT', 'NIGHTS_3_FROM_NOW', name='timevisibility'), nullable=False),
    sa.Column('category', sa.Enum('Perfect', 'Amazing', 'Great', 'Good', 'Ok', 'Bad', 'Terrible', name='sitevisibility'), nullable=False),
    sa.Column('light_pollution', sa.JSON(), nullable=True),
    sa.Column('weather', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_visibility_score'), 'site_visibility', ['score'], unique=False)
    op.create_index('ix_site_visibility_time_bucket', 'site_visibility', ['time_bucket'], unique=False)
    op.create_index('ix_site_visibility_time_score', 'site_visibility', ['time_bucket', 'score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_site_visibility_time_score', table_name='site_visibility')
    op.drop_index('ix_site_visibility_time_bucket', table_name='site_visibility')
    op.drop_index(op.f('ix_site_visibility_score'), table_name='site_visibility')
    op.drop_table('site_visibility')
    # ### end Alembic commands ###
