@url=http://192.168.1.18:3000/
@siteId=3
@lat=48.75
@long=-122.52
@radius = 1000
@name=park
@vis = Terrible
@time = Tonight
@api_key = abc

###Get all sites
GET {{url}}sites?api_key={{api_key}}
Accept: application/json

###Get one site
GET {{url}}site/{{siteId}}?api_key={{api_key}}
Accept: application/json

###Search sites name
GET {{url}}sites/search?name={{name}}&api_key={{api_key}}
Accept: application/json

###Search sites, lat, long, radius
GET {{url}}sites/search?visib={{vis}}&api_key={{api_key}}
Accept: application/json

###Search more
GET {{url}}sites/search?visib={{vis}}&lat=48.7405795&lon=-122.4691099&drive_time=4&time={{time}}&api_key={{api_key}}
Accept: application/json