@lat=48.75
@long=-122.52

@returnAqi=yes

###Replace value with value from localsettings.json
@apiKey = @apiKey = xyz

### Get current weather for Whatcom County, WA
GET http://api.weatherapi.com/v1/current.json?key={{apiKey}}&q={{lat}},{{long}}&aqi={{returnAqi}}
Accept: application/json

### Get future weather for Whatcom County, WA
GET http://api.weatherapi.com/v1/forecast.json?days=1&dt=2026-01-07&hour=22&key={{apiKey}}&q={{lat}},{{long}}&aqi={{returnAqi}}
Accept: application/json